---

name: Build, push and deploy image to Heroku
on:
  push:
    - master
jobs:
  Build-Push-Deploy-Image:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/go-game-of-life:master
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Login Docker
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t ${{ env.DOCKER_IMAGE }} -f Dockerfile.dockerhub .

      - name: Push image
        run: docker push ${{ env.DOCKER_IMAGE }}

      - name: Install Heroku Cli
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
